backend: {name: git-gateway, branch: master}
media_folder: static/images/uploads
public_folder: images/uploads
site_url: http://localhost:1313
locale: en
collections:
- name: homepage
  label: Homepage
  editor: {preview: false}
  files:
  - file: data/homepage/slidesSection.yml
    label: Slides Section
    name: slidesSection
    fields:
    - {name: visible, label: Visible, widget: boolean}
    - label: Slides
      name: slides
      widget: list
      fields:
      - {label: Image, name: image, widget: image}
      - {label: Title, name: title, widget: markdown}
      - {label: Description, name: description, widget: markdown}
      - {label: Url, name: url, widget: string}
      - {label: Button Text, name: button_text, widget: string}
      allow_add: true
  - file: data/homepage/aboutSection.yml
    label: About Section
    name: aboutSection
    fields:
    - {name: visible, label: Visible, widget: boolean}
    - {label: Main Image, name: main_image, widget: image}
    - {label: Title, name: title, widget: string}
    - {label: Description, name: description, widget: markdown}
    - label: Button
      name: button
      widget: object
      fields:
      - {label: Url, name: url, widget: string}
      - {label: Text, name: text, widget: string}
  - file: data/homepage/quoteSection.yml
    label: Quote Section
    name: quoteSection
    fields:
    - {name: visible, label: Visible, widget: boolean}
    - {label: Quote, name: quote, widget: markdown}
    - {label: Name, name: name, widget: string}
  - file: data/homepage/menuSection.yml
    label: Menu Section
    name: menuSection
    fields:
    - {name: visible, label: Visible, widget: boolean}
    - {label: Title, name: title, widget: string}
    - {label: Description, name: description, widget: string}
    - label: Item Types
      name: itemTypes
      widget: list
      fields:
      - {label: Type, name: type, widget: string}
      - {label: Title, name: title, widget: string}
      allow_add: true
    - label: Items
      name: items
      widget: list
      fields:
      - {label: Type, name: type, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: markdown}
      - {label: Price, name: price, widget: string}
      allow_add: true
  - file: data/homepage/gallerySection.yml
    label: Gallery Section
    name: gallerySection
    fields:
    - {name: visible, label: Visible, widget: boolean}
  - file: data/homepage/customerReviewsSection.yml
    label: Customer Reviews Section
    name: customerReviewsSection
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Description, name: description, widget: markdown}
    - label: Customer Reviews
      name: customerReviews
      widget: list
      fields:
      - {label: Headshot, name: headshot, widget: image}
      - {label: Name, name: name, widget: string}
      - {label: Job Title, name: job_title, widget: string}
      - {label: Review, name: review, widget: markdown}
      allow_add: true
    - {label: Previous Text, name: previous_text, widget: string}
    - {label: Next Text, name: next_text, widget: string}
  - file: data/homepage/contactSection.yml
    label: Contact Section
    name: contactSection
    fields:
    - {name: visible, label: Visible, widget: boolean}
    - {label: Phone Title, name: phone_title, widget: string}
    - {label: Email Title, name: email_title, widget: string}
    - {label: Location Title, name: location_title, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
    - label: Params
      name: params
      widget: object
      fields:
      - {label: Icon, name: icon, widget: string}
      - {label: Plugins, name: plugins, widget: hidden}
      - {label: Logo, name: logo, widget: string}
      - label: Footer About Us
        name: footerAboutUs
        widget: object
        fields:
        - {name: visible, label: Visible, widget: boolean}
        - {label: Title, name: title, widget: string}
        - {label: Description, name: description, widget: markdown}
      - label: Opening Hours
        name: openingHours
        widget: object
        fields:
        - {label: Title, name: title, widget: string}
        - label: Hours
          name: hours
          widget: list
          fields:
          - {label: Days, name: days, widget: string}
          - {label: Time, name: time, widget: string}
          allow_add: true
      - label: Contact
        name: contact
        widget: object
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Address, name: address, widget: string}
        - {label: Number, name: number, widget: string}
        - {label: Email, name: email, widget: string}
        - label: Social
          name: social
          widget: list
          fields:
          - {label: Name, name: name, widget: string}
          - {label: Url, name: url, widget: string}
          - {label: Icon, name: icon, widget: string}
          allow_add: true
      - {label: Copyright, name: copyright, widget: markdown}
    - {label: Menu, name: menu, widget: hidden}
- name: aboutPage
  label: About Page
  editor: {preview: false}
  files:
  - file: data/aboutPage/general.yml
    label: General
    name: general
    fields:
    - {label: Title, name: title, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
- name: contactPage
  label: Contact Page
  editor: {preview: false}
  files:
  - file: data/contactPage/general.yml
    label: General
    name: general
    fields:
    - {label: Title, name: title, widget: string}
    - label: Reservation
      name: reservation
      widget: object
      fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: markdown}
      - label: Form
        name: form
        widget: object
        fields:
        - {label: Name Placeholder, name: name_placeholder, widget: string}
        - {label: Email Placeholder, name: email_placeholder, widget: string}
        - {label: Select Placeholder, name: select_placeholder, widget: string}
        - {label: Message Placeholder, name: message_placeholder, widget: string}
        - {label: Button Text, name: button_text, widget: string}
    - label: Map
      name: map
      widget: object
      fields:
      - {label: Lat, name: lat, widget: string}
      - {label: Lng, name: lng, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Info, name: info, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
- name: galleryPage
  label: Gallery Page
  editor: {preview: false}
  files:
  - file: data/galleryPage/general.yml
    label: General
    name: general
    fields:
    - {label: Title, name: title, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
- name: menuPage
  label: Menu Page
  editor: {preview: false}
  files:
  - file: data/menuPage/general.yml
    label: General
    name: general
    fields:
    - {label: Title, name: title, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
- name: reservationPage
  label: Reservation Page
  editor: {preview: false}
  files:
  - file: data/reservationPage/general.yml
    label: General
    name: general
    fields:
    - {label: Title, name: title, widget: string}
    - label: Reservation
      name: reservation
      widget: object
      fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Select Person Text, name: select_person_text, widget: string}
      - {label: Contact Details Text, name: contact_details_text, widget: string}
      - {label: Name Placeholder, name: name_placeholder, widget: string}
      - {label: Email Placeholder, name: email_placeholder, widget: string}
      - {label: Number Placeholder, name: number_placeholder, widget: string}
      - {label: Button Text, name: button_text, widget: string}
- name: settings
  label: Settings
  editor: {preview: false}
  files:
  - file: config.yml
    label: General
    name: general
    fields:
    - {label: baseURL, name: baseURL, widget: hidden}
    - {label: languageCode, name: languageCode, widget: hidden}
    - {label: assetDir, name: assetDir, widget: hidden}
